apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

# Dashboard id 1860 11074
 
# sudo chown -R 472:472 ./monitoring/grafana/provisioning/datasources
# sudo chmod -R 755 ./monitoring/grafana/provisioning/datasources